# Generated by Django 4.0.3 on 2022-08-01 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='firstname',
            field=models.CharField(default='', max_length=100),
        ),
    ]
