# Generated by Django 4.0.3 on 2022-08-01 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0002_tweet_firstname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='firstname',
            field=models.CharField(default='None', max_length=100),
        ),
    ]
